### ISSUE TITLE
PeriodicProducer.cs missing ToLowerInvariant()

### ISSUE THREAD

**Issue by forcecore** [AttacqueSuperior/Engine#17]
https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/PeriodicProducer.cs#L80

Causes crash when the actor to be produced in YAML is defined in capital letters or camel case.

**Comment by GraionDilach** [comment]
Alright, but keep https://github.com/OpenRA/OpenRA/issues/4124 in mind.
