### ISSUE TITLE
Grant timed condition hotkey broken.

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#28]
Also notice aircraft support might be even more bogus, since aircraft are ordered to land by default when using that hotkey.

**Comment by GraionDilach** [comment]
Also... what?

Are you sure that's also AS/Engine issue?

**Comment by GraionDilach** [comment]
NTM: OpenRA/OpenRA#14730.

**Comment by ABrandau** [comment]
The aircraft part is not an AS issue, but its a problem to consider.
