### ISSUE TITLE
PeriodicProducer requires a building queue.

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#33]
Which means that these buildings can also be used as factories in single queue, let me know if I am mistaken.

**Comment by GraionDilach** [comment]
This shouldn't be an issue. BuildAtProductionType should be able to differ the possible and the actually intended exits. Refer to RA1 dog/Kennel vs infantry/Barracks setup for an OpenRA example.

Besides, any other way would require doing separate traits for all delivery methods which is a no-no to me.
