### ISSUE TITLE
Harvest on idle

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#34]
an usual problem of ORA these days is that the harvesters tend to cancel their activities by blocking eachother, a trait that orders them to harvest again after a minute or two would be very handy to solve this, could be conditional so the player can set up wether they want this behaviour or not.

**Comment by forcecore** [comment]
No they arent idle unfortunately. I looked into this in detail but there is no hope haha

https://github.com/OpenRA/OpenRA/pull/13732

https://github.com/OpenRA/OpenRA/pull/12995

Even if you get them to work in field they get stuck at the refinery which invoves docking activity which is also on hold in the PR queue

**Comment by ABrandau** [comment]
That does not involve harvesters being stuck on the resource fields themselves.

**Comment by GraionDilach** [comment]
Is this still the case?

**Comment by GraionDilach** [comment]
Closing since i presume this got fixed upstream.
