### ISSUE TITLE
Fire armament targeting-area marking radius support

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#56]
Basically an Option to draw one or many range circles around the target area, could be cool if they could be colored but that isnt critical.

**Comment by GraionDilach** [comment]
Duplicate of #55.

**Comment by ABrandau** [comment]
No, I was talking about the AoE indicator of the superweapon

**Comment by GraionDilach** [comment]
Oh, sorry. That can be quite complex tbh, considering multi-staged weapons. I'm also notsure if the game supports doing such circular style, think it only supports marking tiles. Gotta check it.
