### ISSUE TITLE
Reworked RadBeam

### ISSUE THREAD

**Issue by forcecore** [AttacqueSuperior/Engine#9]
https://github.com/forcecore/OpenRA/commit/824ccb77aa1e20770593e4a3ebfa42f1ab332480

I've reworked RadBeam to use WAngle instead of my own Sin table and uses QuantizationCount parameter to specify how many dots will we use to draw one cycle. As a good side effect, wave length specified by in WDist is now correctly interpreted.

**Comment by GraionDilach** [comment]
Nice, gotta looki at this tomorrow.
