### ISSUE TITLE
Server implementation leads to GDPR violation by everybody using it

### ISSUE THREAD

**Issue by jrb0001** [AttacqueSuperior/Engine#93]
Upstream https://github.com/OpenRA/OpenRA/issues/17534, relates to #92.

**Comment by GraionDilach** [comment]
This is bad timing for me to sit down and fix all this, but indeed related and indeed requires a fix.

The problem with this one is that I don't want to break the protocol version if possible. I'll probably just cop out and log/transfer 0.0.0.0 where this is used in a way which violates the GDPR.

Clients shouldn't be made aware of the other's IP addresses, that data belongs to the server and the server alone. The only debatable point is if the server should log client IPs - I think this only makes sense for the host, for logging the authorization.

**Comment by jrb0001** [comment]
It won't break the protocol version and there is no need for a dummy value either. Just mark the field so that it is ignored by the serialization to YAML and the client will handle it just fine (shows "Unknown IP" as verified in RV).
