### ISSUE TITLE
From AIDeployNotifier to DeployNotifier

### ISSUE THREAD

**Issue by dnqbob** [AttacqueSuperior/Engine#99]
Hi here, 

Upon using the AIDeployNotifier/AIDeployHelper, I think this function can be normalized. There is a function missing that from Tiberium Sun, which is player can toggle the deployment of deployable vehicles by using attack order. If we make a fake weapon by using AIDeployHelper which works on player,  we can solve most of the problem. 

In conclusion, the new deployment control trait, maybe call it "DeployNotifier", can work for create AI micromanage at bot condition as well as for some units need deployment before attacks.

**Comment by GraionDilach** [comment]
Fair point. I can see this working with dropping the explicit `IsBot` checks for an implicit dependence on `GrantConditionOnBotOwner`.

**Comment by GraionDilach** [comment]
Fixed with https://github.com/AttacqueSuperior/Engine/commit/0322681f1c90f738b109817f6bfe99c8b664dfaa
